#------------------------------------------------------------------------------
# FILE:         action.yaml
# CONTRIBUTOR:  Jeff Lill
# COPYRIGHT:    Copyright (c) 2005-2021 by neonFORGE LLC.  All rights reserved.
#
# The contents of this repository are for private use by neonFORGE, LLC. and may not be
# divulged or used for any purpose by other organizations or individuals without a
# formal written and signed agreement with neonFORGE, LLC.

#------------------------------------------------------------------------------
# Appends a text file to the GitHub action log, optionally nesting the text
# within an expandable group.

name: capture-log
description: "Appends a text file to the GitHub action log, optionally nesting the text within an expandable group"
inputs:
  path:
    description: "The text file path"
    required: true
  group:
    description: "Optionally specifies the group name when nesting within an expandable group"
    required: false
  type: 
    description: "Optionally specifies the log file type for colorization (one of: '', 'none', or 'build-log)"
    required: false
    default: none
  success:
    description: "Optionally indicates whether the step that created the log failed"
    required: false
    default: "true"
  fail-on-error:
    description: "Optionally indicates whether the action should fail after collecting the log when [success] is false"
    required: false
    default: "true"
runs:
  using: node12
  main: action.js
